base_config:
- configs/logging.yaml


ref_mesh  : "data/bob/bob_tri.obj"
random_textures: true
iter: 1
save_interval: 100
texture_res: [ 1024, 1024 ]
train_res: [512, 512]
batch: 4
learning_rate: [0.03, 0.003]
ks_min : [0, 0.0, 0]
envmap: "data/irrmaps/aerodynamics_workshop_2k.hdr"
env_scale : 1.0
background: "black"
validate : True
# out_dir: "output"
# loss: "log1"
