base_config:
- configs/logging.yaml

ref_mesh: "data/customized/pile_turntable"

random_textures: true
iter: 2000
save_interval: 100
display_interval: 20
texture_res: [ 1024, 1024 ]
train_res: [512, 512]
batch: 8
learning_rate: [0.03, 0.003]
ks_min : [0, 0.001, 0.0]

# envmap: "data/irrmaps/abandoned_hopper_terminal_04_2k.hdr"
background: "white"
validate : True

out_dir: "output_llff"
separate_ks: True
add_datetime_prefix: true
display : [{"bsdf":"kd"}]
learn_light : true
# laplace_scale : 3000

loss: "relmse"

kd_loss_1: "logl1"
kd_loss_2 : "smape"
ks_loss_1: "relmse"
ks_loss_2: "mse"


disable_occlusion: false
disable_metallic : false

isosurface : "flexicubes"
# dmtet_grid : 128


mesh_scale : 2.0
