base_config:
- configs/logging.yaml


ref_mesh: "data/spot_1/spot.obj"
ref_textures: "data/spot_1/textures"

random_textures: true
iter: 1000
save_interval: 20
texture_res: [ 1024, 1024 ]
train_res: [512, 512]
batch: 8
learning_rate: [0.03, 0.003]
ks_min : [0, 0.001, 0.0]
# ks_min : [0.001, 0.0]
envmap: "data/irrmaps/aerodynamics_workshop_2k.hdr"
background: "white"
validate : True

out_dir: "output_test"
separate_ks: True
add_datetime_prefix: true

# display : [{"latlong" : true}]
# learn_light : true

learn_light : false


loss: "relmse"

kd_loss_1: "logl1"
kd_loss_2 : "smape"
ks_loss_1: "relmse"
ks_loss_2: "mse"


disable_occlusion: true
disable_metallic: true

isosurface : "flexicubes"
dmtet_grid : 48